[pytest]
# On force pytest à ne regarder QUE ton dossier d'exercice
testpaths = .
# On lui dit d'ignorer les fichiers du livre pour ne pas être pollué
norecursedirs = fichiers_livre .venv
python_files = test_*.py
