[pytest]
# On force pytest à ne regarder QUE le dossier d'exercice
testpaths = .
# On lui dit d'ignorer les fichiers du livre pour ne pas être pollué
norecursedirs = livre_tiny_python_projects .venv
python_files = test_*.py
